name: collector-worker
app: node@22
env:
  - WORKER_ROLE: collector
  - SUPABASE_URL: "${SUPABASE_URL}"
  - SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
  - YOUTUBE_API_KEY_1: "${YOUTUBE_API_KEY_1}"
command: node worker-runner.cjs
---
name: tubiq-web-relay
app: python@3.11
version: v2
command: python main.py
start: python main.py
context: tubiq-web-relay
port: 8080
env:
  - SUPABASE_URL: "${SUPABASE_URL}"
  - SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
  - SUPABASE_TABLE_VIDEOS: "relay_videos"
  - SUPABASE_UPSERT_ON_CONFLICT: "account_id,platform,external_id"
  - SUPABASE_VIDEOS_MODE: "relay"
  - PORT: "8080"
---
name: relay-metadata-worker
app: node@22
env:
  - WORKER_ROLE: relay-metadata
  - SUPABASE_URL: "${SUPABASE_URL}"
  - SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
  - YOUTUBE_API_KEY_1: "${YOUTUBE_API_KEY_1}"
  - POLL_INTERVAL_SEC: "10"
  - BATCH_SIZE: "50"
command: node worker-runner.cjs
